services:
  {{ name_of_service_pg }}:
    image: postgres
    container_name: postgres-docker
    restart: always
    environment:
      - POSTGRES_USER={{ pg_user }}
      - POSTGRES_PASSWORD={{ pg_pwd }}
    volumes:
      - {{ path_db }}/{{ pg_user }}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  {{ name_of_service_nginx }}:
    image: nginx
    container_name: nginx-docker
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 443:443
    volumes:
      - {{path_nginx}}/{{ url_connector }}.conf:/etc/nginx/conf.d/{{ url_connector }}.conf
      - {{path_nginx}}/ssl:/etc/nginx/ssl
      - {{path_nginx}}/logs_nginx:/var/log/nginx

  {{ name_of_service_connector }}:
    image: permalexeyy/connector3
    container_name: connector-docker
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 5050:5000
    depends_on:
      - {{ name_of_service_pg }}
      - {{ name_of_service_nginx }}
    volumes:
      - {{ path_connector }}/logs:/app/__Logs
      - {{ path_connector }}/appsettings.json:/app/appsettings.json
