---
- name: Install required system packages
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - apt-transport-https
    update_cache: true

- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release }} stable"
#    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Run the equivalent of "apt update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker-compose
#    - docker
#    - docker.io
#    - python3-docker
    update_cache: true

- name: Download latest version of docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ansible_system | lower}}-{{ansible_architecture}}"
    dest: /usr/local/bin/docker-compose
    mode: '0441'

- name: Create a directory {{ path_docker }} if it does not exist
  ansible.builtin.file:
    path: "{{ path_docker }}"
    state: directory

- name: Copy Docker Compose files
  ansible.builtin.template:
    src: /etc/ansible/roles/pg_ng_in_docker/templates/docker-compose.yml
    dest: "{{ path_docker }}/docker-compose.yml"

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ path_docker }}"
    files:
    - docker-compose.yml
