---
- name: Install required system packages
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    update_cache: true
 
- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
 
- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_distribution_release }} stable"
    state: present
     
- name: Install docker
  ansible.builtin.apt:
    pkg:
    - docker
    - docker.io
    - python3-docker
    - docker-compose
    update_cache: true
 
- name: Download docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ansible_system | lower}}-{{ansible_architecture}}"    
    dest: /usr/local/bin/docker-compose
    mode: '0441'

- name: Create a directory {{ path_docker }} if it does not exist
  ansible.builtin.file:
    path: "{{ path_docker }}"
    state: directory

- name: copy Docker Compose files
  ansible.builtin.template:
    src: /etc/ansible/roles/postgres_in_docker/templates/docker-compose.yml
    dest: "{{ path_docker }}/docker-compose.yml"

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ path_docker }}"
    files:
    - docker-compose.yml
