services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER="{{ pg_user }}"
      - POSTGRES_PASSWORD="{{ pg_pwd }}"
    volumes:
      - /opt/soft/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
