--- 
- name: Create a directory {{ path_connector }} if it does not exist
  ansible.builtin.file:
    path: "{{ path_connector }}/logs"
    state: directory
   
- name: Copy appsettings.json
  template:
    src: /etc/ansible/roles/pg_ng_con_in_docker/templates/appsettings.json
    dest: "{{path_connector}}/appsettings.json"
