---
- name: Block install soft
  block:
     - name: Install postgresql
       apt:
         name=postgresql
         state=present
     - name: Install psycopg2
       apt:
         name=python3-psycopg2
         state=present
     - name: Install acl
       apt:
         name=acl
         state=present
  when:
    ansible_os_family == "Debian"


- name: Find path for hba_file
  shell: su postgres -c "psql -t -P format=unaligned -c 'show hba_file'"
  register: pg_hba_file

- name: Add entries to pg_hba
  community.postgresql.postgresql_pg_hba:
    dest: "{{ pg_hba_file.stdout }}"
    address: "{{ item.address | default(omit) }}"
    contype: "{{ item.contype }}"
    method: "{{ item.method }}"
  with_items: "{{ postgresql_hba_entries }}"

- name: Set options listen_addresses and max_connections
  community.postgresql.postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  become: true
  become_user: postgres
  with_items: "{{ postgresql_options }}"

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    enabled: yes
    state: restarted

- name: Create postgresql user
  postgresql_user:
    user: "{{ pg_user }}"
    password: "{{ pg_pwd }}"
    role_attr_flags: "CREATEDB,SUPERUSER"
  become: true
  become_user: postgres
